# Generated by Django 2.2.5 on 2022-05-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Pet',
        ),
    ]
