# Generated by Django 2.2.5 on 2022-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20220510_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='content',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='pet',
            name='genre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
