# Generated by Django 2.2.5 on 2022-05-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20220517_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.TextField(),
        ),
    ]
