# Generated by Django 2.2.5 on 2022-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20220518_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.TextField(),
        ),
    ]
